/* pawn-test
 * A ridiculously simple automated testing framework for PAWN scripts.
 *
 * Copyright (c) 2015 Pék Marcell
 * This project is covered by the MIT License, see the attached LICENSE
 * file for more details.
 *
 * pawn-test.inc - the pawn-test bootstrapper
 *
 */

#include <pawn-test/config>

#include <pawn-test/main>
#include <pawn-test/suite-case-init-destroy>
#include <pawn-test/private-funcs>
#include <pawn-test/test-functions>
#include <pawn-test/test-runner>